apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort  # Use LoadBalancer if on a cloud provider like AWS/GKE
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80          # Exposes port 80 externally
      targetPort: 3000  # The port your app runs on inside the container